#!/bin/bash

([[ $# != "5" ]] && echo "Usage: ydm <youtube link> <artist> <title> <album> <download dir>") || ([[ $# == "5" ]] && youtube-dl -o "$5/$2-$3.m4a" -f 140 $1 && taffy -r "$2" -t "$3" -l "$4" "$5/$2-$3.m4a")
